### ISSUE TITLE
fd cannot be null

### ISSUE THREAD

**Issue by GohelAshok701** [UttamPanchasara/PDF-Generator#14]
@UttamPanchasara 

I hope you are doing great!!

**Fatal Exception: java.lang.IllegalArgumentException
fd cannot be null**

Fatal Exception: java.lang.IllegalArgumentException: fd cannot be null
       at dp.onWrite(dp.java:27)
       at android.print.PdfPrint$1.onLayoutFinished(PdfPrint.java:30)
       at dp.onLayout(dp.java:4)
       at android.print.PdfPrint.print(PdfPrint.java:18)
       at com.uttampanchasara.pdfgenerator.CreatePdf.savePdf(CreatePdf.java:101)
       at com.uttampanchasara.pdfgenerator.CreatePdf.access$savePdf(CreatePdf.java)
       at com.uttampanchasara.pdfgenerator.CreatePdf$create$1.onPageFinished(CreatePdf.java:30)
       at O7.b(O7.java:2)
       at Do.handleMessage(Do.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:228)
       at android.app.ActivityThread.main(ActivityThread.java:7819)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)

I'm facing like this error, can you please give me any solution?

Thanks
Ashok

**Comment by UttamPanchasara** [comment]
@GohelAshok701 Is it happening when you try to get pdf?

**Comment by GohelAshok701** [comment]
Yes, but getting this issue on some devices.

Brand: realme
Model: realme 6Pro
Orientation: Portrait
RAM free: 3.83 GB
Disk free: 97.08 GB
Operating System
Version: 10
Orientation: Portrait
Rooted: No

**Comment by UttamPanchasara** [comment]
Thanks for the detail, I will verify the same

**Comment by GohelAshok701** [comment]
@UttamPanchasara  Thanks for your response.

This issue getting due to Android Version 10.

Now fixed.

I have added the below line in manifest under the application tag.

_android:requestLegacyExternalStorage="true"_


Thanks.

**Comment by pratamawijaya** [comment]
@GohelAshok701 hi, iam getting error same as you, and trying to add `android:requestLegacyExternalStorage="true"`

but its still force close
```
2020-06-18 14:02:20.374 16575-16575/com.coba.htmltopdf E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.coba.htmltopdf, PID: 16575
    java.lang.IllegalArgumentException: fd cannot be null
        at ft.onWrite(chromium-TrichromeWebViewGoogle.apk-stable-410409683:28)
        at android.print.PdfPrint$1.onLayoutFinished(PdfPrint.java:21)
        at ft.onLayout(chromium-TrichromeWebViewGoogle.apk-stable-410409683:4)
        at android.print.PdfPrint.print(PdfPrint.java:18)
        at com.uttampanchasara.pdfgenerator.CreatePdf.savePdf(CreatePdf.kt:129)
        at com.uttampanchasara.pdfgenerator.CreatePdf.access$savePdf(CreatePdf.kt:19)
        at com.uttampanchasara.pdfgenerator.CreatePdf$create$1.onPageFinished(CreatePdf.kt:102)
        at Fa.b(chromium-TrichromeWebViewGoogle.apk-stable-410409683:2)
        at Cs.handleMessage(chromium-TrichromeWebViewGoogle.apk-stable-410409683:65)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by Sanket911** [comment]
@UttamPanchasara , Hope you doing well!

I am getting the same error despite adding **android:requestLegacyExternalStorage="true"** . 

Running it on older device - Android 8.1.0

**/PdfPrint: Failed to open ParcelFileDescriptor
    java.io.IOException: No such file or directory**
        at java.io.UnixFileSystem.createFileExclusively0(Native Method)
        at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
        at java.io.File.createNewFile(File.java:1000)
        at android.print.PdfPrint.getOutputFile(PdfPrint.java:45)
        at android.print.PdfPrint.access$000(PdfPrint.java:9)
        at android.print.PdfPrint$1.onLayoutFinished(PdfPrint.java:21)

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.pdfmybills, PID: 30165
    java.lang.IllegalArgumentException: fd cannot be null
        at Ny0.onWrite(chromium-Monochrome.aab-stable-414708973:28)
        at android.print.PdfPrint$1.onLayoutFinished(PdfPrint.java:21)
        at Ny0.onLayout(chromium-Monochrome.aab-stable-414708973:4)
        at android.print.PdfPrint.print(PdfPrint.java:18)
        at com.uttampanchasara.pdfgenerator.CreatePdf.savePdf(CreatePdf.kt:129)
        at com.uttampanchasara.pdfgenerator.CreatePdf.access$savePdf(CreatePdf.kt:19)
        at com.uttampanchasara.pdfgenerator.CreatePdf$create$1.onPageFinished(CreatePdf.kt:102)
        at oo.b(chromium-Monochrome.aab-stable-414708973:2)
        at ky0.handleMessage(chromium-Monochrome.aab-stable-414708973:66)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6635)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by Satishkumar591** [comment]
I too had the same issue, I fixed the issue by changing the Gradle(app) compileSdkVersion from 30 to 29 and targetSdkVersion from 30 to 29.

Issue Fixed
