### ISSUE TITLE
Crash with error :  No such file or directory PdfPrint

### ISSUE THREAD

**Issue by Sanket911** [UttamPanchasara/PDF-Generator#18]
@UttamPanchasara , Hope you doing well!

I am getting the same error despite adding **android:requestLegacyExternalStorage="true" .**

Running it on older device - **Android 8.1.0**

/PdfPrint: Failed to open ParcelFileDescriptor
java.io.IOException: No such file or directory
at java.io.UnixFileSystem.createFileExclusively0(Native Method)
at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
at java.io.File.createNewFile(File.java:1000)
at android.print.PdfPrint.getOutputFile(PdfPrint.java:45)
at android.print.PdfPrint.access$000(PdfPrint.java:9)
at android.print.PdfPrint$1.onLayoutFinished(PdfPrint.java:21)

E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.example.pdfmybills, PID: 30165
java.lang.IllegalArgumentException: fd cannot be null
at Ny0.onWrite(chromium-Monochrome.aab-stable-414708973:28)
at android.print.PdfPrint$1.onLayoutFinished(PdfPrint.java:21)
at Ny0.onLayout(chromium-Monochrome.aab-stable-414708973:4)
at android.print.PdfPrint.print(PdfPrint.java:18)
at com.uttampanchasara.pdfgenerator.CreatePdf.savePdf(CreatePdf.kt:129)
at com.uttampanchasara.pdfgenerator.CreatePdf.access$savePdf(CreatePdf.kt:19)
at com.uttampanchasara.pdfgenerator.CreatePdf$create$1.onPageFinished(CreatePdf.kt:102)
at oo.b(chromium-Monochrome.aab-stable-414708973:2)
at ky0.handleMessage(chromium-Monochrome.aab-stable-414708973:66)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:176)
at android.app.ActivityThread.main(ActivityThread.java:6635)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by UttamPanchasara** [comment]
Make sure in providing proper directory path, if you're giving custom path then please add file read/write permission as well if you have not added.

**Comment by Husseinhj** [comment]
As @UttamPanchasara said, You should grant permission to read or write from external storage like this [answer](https://stackoverflow.com/a/52993580/5229540).

**Comment by UttamPanchasara** [comment]
Hope issue was due to permission only, closing this.
